### ISSUE TITLE
Train Relational Networks for 10 epochs

### ISSUE THREAD

**Issue by xunhuang1995** [kimhc6028/relational-networks#1]
I have trained RN for 10 epochs. The final test set accuracy is 73% for relational question and 72% for non-relational question. It seems that there is no significant improvement for relational questions.

**Comment by kimhc6028** [comment]
CNN + MLP (Not RN) scored approximately 44% on relational questions. I guess relational networks does improves relational questions, but I might forgot or mistook some settings. I am working on it currently.

**Comment by justinbuzzni** [comment]
I have trained RN for 20 epochs. The last test set accuracy is 84% for relation question and 93% for non-relational questions.

**Comment by kimhc6028** [comment]
@justinbuzzni Would you please PR the trained model after 20 epochs? This should be saved at /model/epoch_20.pth

**Comment by kimhc6028** [comment]
I chaned the architecture, and the result is written in the README. If any other things come out, please reopen this issue.
