### ISSUE TITLE
Dealing with pixels misunderstanding ?

### ISSUE THREAD

**Issue by phongnhhn92** [kimhc6028/relational-networks#10]
Hello sir, 
I am reading the paper and your code. However there is one thing I dont understand from your implementation.
In the paper, at the Section 4 (Dealing with pixels), the author said that: "So after convolving the image, each of the d2 k-dimensional cells in the d x d feature maps was tagged with an arbitrary coordinate ...". So my question is in your code, which part is referring to this and would you please explain more about it since it is kind a difficult for me to understand it. Thanks !

**Comment by shamitlal** [comment]
Check out the lines 47-53 in model.py. Author has generated the coordinates here. The coordinates are then concatenated with the feature map vectors in lines 77-78.

**Comment by kimhc6028** [comment]
Sorry for late reply. In the newest master branch, line 107-117 in model.py prepares coordinates tensor, and line 136 assigns coordinates to feature vector. Thank you, and reopening this issue is always welcome!
