### ISSUE TITLE
About coord_tensor and np_coord_tensor part in model.py

### ISSUE THREAD

**Issue by bazingasherlock** [kimhc6028/relational-networks#11]
Hi, the code is almost completely self-explanatory. However, I couldn't understand [this](https://github.com/kimhc6028/relational-networks/blob/master/model.py#L43-L50) part. Could you explain there ? Why you're creating `coord_tensor` and `np_coord_tensor` and what is the number 25 there ? I also would like to hear about lines 48-49-50.
**Edit:**
I have also another question about the implementation. Eventhough it is completely differ'rent, I don't want to open one more issue :) 
I guess `translator.py` file and function inside of it isn't used anywhere in the code. What was the aim of that file ?

**Comment by shamitlal** [comment]
The Author generated the coordinates of each cell of the 5X5 feature map. These coordinates are then concatenated with the feature map vectors in lines 77-78 of model.py. Just print the values returned by cvt_coord function.
25 is 5 squared. Final feature map has spatial dimension 5X5. The Paper mentions trying every pair of feature map vector. So this gives a total of 25 pairs.

**Comment by kimhc6028** [comment]
Hi, I apolozie for late reply. I only have a few hours between training. Translator.py is not used in any code. I added this file to make it easier to understand vectorized question into human language. Basically, if you are not interested, you can ignore this file. Thank you

**Comment by kimhc6028** [comment]
I close this issue because many changes have been made by other contributor. Please reopen if any you have any issue on newest implementation of RN. Thank you!

**Comment by vardaan123** [comment]
@shamitlal Could you please help me better understand the coord tensor. It looks like this
```
array([[-1. , -1. ],
       [-0.9, -0.5],
       [-0.8,  0. ],
       [-0.7,  0.5],
       [-0.6,  1. ],
       [-0.5, -1. ],
       [-0.4, -0.5],
       [-0.3,  0. ],
       [-0.2,  0.5],
       [-0.1,  1. ],
       [ 0. , -1. ],
       [ 0.1, -0.5],
       [ 0.2,  0. ],
       [ 0.3,  0.5],
       [ 0.4,  1. ],
       [ 0.5, -1. ],
       [ 0.6, -0.5],
       [ 0.7,  0. ],
       [ 0.8,  0.5],
       [ 0.9,  1. ],
       [ 1. , -1. ],
       [ 1.1, -0.5],
       [ 1.2,  0. ],
       [ 1.3,  0.5],
       [ 1.4,  1. ]])
```
How are these co-ordinates or even normalized co-ordinates? The first dim. is probably okay but what about the second dim, that is being generated by modulo.`[(i/5-2)/2., (i%5-2)/2.]`
