### ISSUE TITLE
Variables and their requires_grad flags

### ISSUE THREAD

**Issue by bazingasherlock** [kimhc6028/relational-networks#12]
Why all of your variables [here](https://github.com/kimhc6028/relational-networks/blob/d19ebacb7e2a576e813a3ebac3fecd31ba3e9215/main.py#L55-L57) and [here](https://github.com/kimhc6028/relational-networks/blob/78319e22ad4d9b7a361dd846d2ac5f8f1e8e92d9/model.py#L39-L46)'s `requires_grad` argumand set to `False` ? You set `requires_grad` parameter of `coord_tensor` variable to `false` and then you concatenate it with the output of cnn (defined as `x`),whose `requires_grad` arguman is  `true` by default _I guess_,  at line [78](https://github.com/kimhc6028/relational-networks/blob/78319e22ad4d9b7a361dd846d2ac5f8f1e8e92d9/model.py#L78). In this case what is the `requires_grad` parameter of concatenated variable (output of line 78 which is also `x_flat`)?

**Comment by kimhc6028** [comment]
Sorry, currently I cannot answer this question now because I am under military training. I promise to answer it 3 weeks later. Please wait until then

**Comment by kimhc6028** [comment]
I couldn't find any requires_grad parameters set to be true or false. As far as I know, setting required_grad to be false is only required when you want to fix certain layer. RN is end-to-end learning system, so I suspect I didn't need to set any reuiqres_grad to be false. If I am wrong, please tell me.
