### ISSUE TITLE
Encoding the question.

### ISSUE THREAD

**Issue by AashishV** [kimhc6028/relational-networks#14]
In the model, there is no inclusion of an LSTM. How is the question then encoded? @gngdb Do you have any idea about this?

**Comment by gngdb** [comment]
The toy problem of `sort_of_clevr` provides the question as a binary vector to start with, see https://github.com/kimhc6028/relational-networks/blob/master/sort_of_clevr_generator.py#L98-L101

The work in the paper on the full clevr dataset hasn't been replicated here, and that would require an LSTM or something similar for the question embedding.

**Comment by AashishV** [comment]
Thank you for the clarification.
