### ISSUE TITLE
AMI to run the code 

### ISSUE THREAD

**Issue by bazingasherlock** [kimhc6028/relational-networks#7]
Hi, is there any public AMI on amazon so that we can try the code ? I cannot run your code a couple of different pytorch AMIs since I got a couple of errors inside the main.py file.

**Comment by kimhc6028** [comment]
Hi, I have never used AMI, so I have no knowledge about it. But RN is not doing something really complicated, so I guess you can run this code if you can run simplest pytorch codes. Could you show me error messages?

**Comment by bazingasherlock** [comment]
So interesting.. I use  [this](https://github.com/ritchieng/dlami) AMI on the web. For the first time I run it, I was getting :

> RuntimeError: cublas runtime error : the GPU program failed to execute at /b/wheel/pytorch-src/torch/lib/THC/THCBlas.cu:246 

error (Since I closed the terminal I cannot give you to all backtrace). However now, I'm able to run the code without getting error(I didnot change anything at all) : 
directory ./data already exists
building test datasets...
building train datasets...
saving datasets...
datasets saved at ./data/sort-of-clevr.pickle
loading data...
processing data...
directory ./model already exists
Train Epoch: 1 [0/196000 (0%)] Relations accuracy: 0% | Non-relations accuracy: 16%
Train Epoch: 1 [1280/196000 (1%)] Relations accuracy: 30% | Non-relations accuracy: 23%
Train Epoch: 1 [2560/196000 (1%)] Relations accuracy: 36% | Non-relations accuracy: 45%
Train Epoch: 1 [3840/196000 (2%)] Relations accuracy: 31% | Non-relations accuracy: 47%
Train Epoch: 1 [5120/196000 (3%)] Relations accuracy: 41% | Non-relations accuracy: 52%
Train Epoch: 1 [6400/196000 (3%)] Relations accuracy: 36% | Non-relations accuracy: 38%
Train Epoch: 1 [7680/196000 (4%)] Relations accuracy: 45% | Non-relations accuracy: 39%
Train Epoch: 1 [8960/196000 (5%)] Relations accuracy: 42% | Non-relations accuracy: 53%
Train Epoch: 1 [10240/196000 (5%)] Relations accuracy: 52% | Non-relations accuracy: 55%
Train Epoch: 1 [11520/196000 (6%)] Relations accuracy: 41% | Non-relations accuracy: 53%
Train Epoch: 1 [12800/196000 (7%)] Relations accuracy: 42% | Non-relations accuracy: 53%
Train Epoch: 1 [14080/196000 (7%)] Relations accuracy: 39% | Non-relations accuracy: 48%
Train Epoch: 1 [15360/196000 (8%)] Relations accuracy: 59% | Non-relations accuracy: 52%
Train Epoch: 1 [16640/196000 (8%)] Relations accuracy: 44% | Non-relations accuracy: 58%
Train Epoch: 1 [17920/196000 (9%)] Relations accuracy: 55% | Non-relations accuracy: 48%
Train Epoch: 1 [19200/196000 (10%)] Relations accuracy: 44% | Non-relations accuracy: 55%
Train Epoch: 1 [20480/196000 (10%)] Relations accuracy: 45% | Non-relations accuracy: 48%
Train Epoch: 1 [21760/196000 (11%)] Relations accuracy: 58% | Non-relations accuracy: 45%

**Comment by kimhc6028** [comment]
It is nice to hear that it works. Have fun with RN! :)
