### ISSUE TITLE
Magic Number Question

### ISSUE THREAD

**Issue by talbaumel** [kimhc6028/relational-networks#8]
Hi, in line 21 I had a hard time understanding the calculation
`(24+2)*2+11`
The input of the linear layer should be two objects each encoded as a vector size of 24.
Where did the  +2 and +11 came from?

Thanks!

**Comment by kimhc6028** [comment]
Hi. +2 means x,y coordinate of the input object. And +11 is number of question vector. You can see that question vector is concatenated to object vectors at [line 74](https://github.com/kimhc6028/relational-networks/blob/master/model.py#L74)

**Comment by talbaumel** [comment]
Got it
Thanks!
